// @ts-nocheck

/**
 * docs页面配置
 */
import { Config, NavsItem } from '@byted/bydesign-docs-vue';

import changeLogIcon from './components/menu_icons/changelog.svg';
import changeLogIconActive from './components/menu_icons/changelog_active.svg';
import quickstartIcon from './components/menu_icons/quickstart.svg';
import quickstartIconActive from './components/menu_icons/quickstart_active.svg';
import compIcon from './components/menu_icons/comp.svg';
import compIconActive from './components/menu_icons/comp_active.svg';
import themeIcon from './components/menu_icons/theme.svg';
import themeIconActive from './components/menu_icons/theme_active.svg';
import i18nIcon from './components/menu_icons/i18n.svg';
import i18nIconActive from './components/menu_icons/i18n_active.svg';
import introIcon from './components/menu_icons/intro.svg';
import introIconActive from './components/menu_icons/intro_active.svg';
import brandIcon from './components/menu_icons/brand.svg';
import brandIconActive from './components/menu_icons/brand_active.svg';

interface TypeConfig {
  [key: string]: Config;
}

const config: TypeConfig = {
  'zh-CN': {
    logo: 'https://s2.pstatp.com/cdn/expire-1-m/byted-creative-app/static/byted-logo.svg',
    navs: [
      {
        label: '介绍',
        path: '/intro',
        activeIcon: introIconActive,
        defaultIcon: introIcon,
      },
      {
        label: '快速上手',
        path: '/quickstart',
        activeIcon: quickstartIconActive,
        defaultIcon: quickstartIcon,
      },
      {
        label: '更新日志',
        path: '/changelog',
        activeIcon: changeLogIconActive,
        defaultIcon: changeLogIcon,
      },
      {
        label: '主题定制',
        path: '/theme',
        activeIcon: themeIconActive,
        defaultIcon: themeIcon,
      },
      {
        label: '品牌定制',
        path: '/brand',
        defaultIcon: brandIcon,
        activeIcon: brandIconActive,
      },
      {
        label: '国际化',
        path: '/internationalization',
        activeIcon: i18nIconActive,
        defaultIcon: i18nIcon,
      },
      {
        label: '组件',
        activeIcon: compIconActive,
        defaultIcon: compIcon,
        list: [
          {
            label: '基础组件',
            list: [
              {
                label: 'Button 按钮',
                path: '/button',
                anchors: [
                  { id: '按钮', label: '按钮' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '类型', label: '类型' },
                  { id: '描边', label: '描边' },
                  { id: '半透明', label: '半透明' },
                  { id: '细边框', label: '细边框' },
                  { id: '禁用态', label: '禁用态' },
                  { id: '形状', label: '形状' },
                  { id: '尺寸', label: '尺寸' },
                  { id: '文字按钮', label: '文字按钮' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Popup 弹出层',
                path: '/popup',
                anchors: [
                  { id: '弹出层', label: '弹出层' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '插入body节点', label: '插入body节点' },
                  { id: '弹出位置', label: '弹出位置' },
                  { id: '指定挂载位置', label: '指定挂载位置' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Cell 单元格',
                path: '/cell',
                anchors: [
                  { id: '单元格', label: '单元格' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '单元格大小', label: '单元格大小' },
                  { id: '箭头方向', label: '箭头方向' },
                  { id: '只设置 value', label: '只设置 value' },
                  { id: '分组标题', label: '分组标题' },
                  { id: '高级用法', label: '高级用法' },
                  { id: 'API', label: 'API' },
                  { id: 'CellGroup Props', label: 'CellGroup Props' },
                  { id: 'Cell Props', label: 'Cell Props' },
                  { id: 'Cell Events', label: 'Cell Events' },
                  { id: 'Cell Slots', label: 'Cell Slots' },
                ],
              },
              {
                label: 'Row-Col Layout 行列布局',
                path: '/col',
                anchors: [
                  { id: '布局', label: '布局' },
                  { id: '介绍', label: '介绍' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '设置列元素间距', label: '设置列元素间距' },
                  { id: 'Flex布局', label: 'Flex布局' },
                  { id: 'API', label: 'API' },
                  { id: 'Row Props', label: 'Row Props' },
                  { id: 'Col Props', label: 'Col Props' },
                ],
              },
            ],
          },
          {
            label: '反馈组件',
            list: [
              {
                label: 'SwipeCell 滑动单元格',
                path: '/swipe-cell',
                anchors: [
                  { id: '滑动单元格', label: '滑动单元格' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '异步关闭', label: '异步关闭' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Slots', label: 'Slots' },
                  { id: 'Events', label: 'Events' },
                  { id: 'close Params', label: 'close Params' },
                  { id: 'Methods', label: 'Methods' },
                ],
              },
              {
                label: 'Toast 轻提示',
                path: '/toast',
                anchors: [
                  { id: '轻提示', label: '轻提示' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '提示文字', label: '提示文字' },
                  { id: '成功/失败/警告/加载', label: '成功/失败/警告/加载' },
                  { id: '设置时间', label: '设置时间' },
                  { id: '禁止背景点击', label: '禁止背景点击' },
                  { id: '按需引入设置内置函数名称', label: '按需引入设置内置函数名称' },
                  { id: 'API', label: 'API' },
                  { id: 'Options', label: 'Options' },
                ],
              },
              {
                label: 'Dialog 对话框',
                path: '/message-box',
                anchors: [
                  { id: '对话框', label: '对话框' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '提示弹框', label: '提示弹框' },
                  { id: '确认弹框', label: '确认弹框' },
                  { id: '多种操作', label: '多种操作' },
                  { id: '按需引入设置内置函数名称', label: '按需引入设置内置函数名称' },
                  { id: 'Options', label: 'Options' },
                  { id: '自定义对话框', label: '自定义对话框' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '异步关闭', label: '异步关闭' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Slots', label: 'Slots' },
                ],
              },
              {
                label: 'NoticeBar 通知栏',
                path: '/notice-bar',
                anchors: [
                  { id: '通知栏', label: '通知栏' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '关闭用法', label: '关闭用法' },
                  { id: '溢出省略', label: '溢出省略' },
                  { id: '风格样式', label: '风格样式' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Slots', label: 'Slots' },
                ],
              },
              {
                label: 'ActionSheet 上拉菜单',
                path: '/action-sheet',
                anchors: [
                  { id: '上拉菜单', label: '上拉菜单' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '选项状态', label: '选项状态' },
                  { id: '展示取消按钮', label: '展示取消按钮' },
                  { id: '展示标题栏', label: '展示标题栏' },
                  { id: '额外插槽', label: '额外插槽' },
                  { id: 'API', label: 'API' },
                  { id: 'Types', label: 'Types' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Scoped Slots', label: 'Scoped Slots' },
                ],
              },
              {
                label: 'Dropdown 下拉菜单',
                path: '/dropdown',
                anchors: [
                  { id: '下拉菜单', label: '下拉菜单' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '向上展开', label: '向上展开' },
                  { id: '禁用菜单', label: '禁用菜单' },
                  { id: '自定义菜单内容', label: '自定义菜单内容' },
                  { id: '标题插槽', label: '标题插槽' },
                  { id: 'API', label: 'API' },
                  { id: 'Dropdown Props', label: 'Dropdown Props' },
                  { id: 'DropdownItem Props', label: 'DropdownItem Props' },
                  { id: 'DropdownItem Events', label: 'DropdownItem Events' },
                  { id: 'DropdownItem Slots', label: 'DropdownItem Slots' },
                  { id: 'DropdownItem', label: 'DropdownItem' },
                  { id: 'Option', label: 'Option' },
                ],
              },
              {
                label: 'Sliding loading 滑动加载',
                path: '/pull-refresh',
                anchors: [
                  { id: '下拉刷新', label: '下拉刷新' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Slots', label: 'Slots' },
                ],
              },
            ],
          },
          {
            label: '表单组件',
            list: [
              {
                label: 'Option 选择项',
                path: '/checker',
                anchors: [
                  { id: '选择项', label: '选择项' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '单选类型', label: '单选类型' },
                  { id: '单选异步', label: '单选异步' },
                  { id: '形状类型', label: '形状类型' },
                  { id: '样式类型', label: '样式类型' },
                  { id: '显示信息', label: '显示信息' },
                  { id: '设置禁用', label: '设置禁用' },
                  { id: '尺寸大小', label: '尺寸大小' },
                  { id: 'API', label: 'API' },
                  { id: 'Checker Props', label: 'Checker Props' },
                  { id: 'CheckerItem Props', label: 'CheckerItem Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Switch 开关',
                path: '/switch',
                anchors: [
                  { id: '开关', label: '开关' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '禁用状态', label: '禁用状态' },
                  { id: '尺寸大小', label: '尺寸大小' },
                  { id: '控制事件', label: '控制事件' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Radio 单选框',
                path: '/radio',
                anchors: [
                  { id: '单选框', label: '单选框' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '风格样式', label: '风格样式' },
                  { id: '尺寸大小', label: '尺寸大小' },
                  { id: '禁用状态', label: '禁用状态' },
                  { id: '异步用法', label: '异步用法' },
                  { id: '组合用法', label: '组合用法' },
                  { id: 'API', label: 'API' },
                  { id: 'Radio Props', label: 'Radio Props' },
                  { id: 'RadioGroup Props', label: 'RadioGroup Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'RadioGroup Events', label: 'RadioGroup Events' },
                  { id: '选择项', label: '选择项' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '单选类型', label: '单选类型' },
                  { id: '单选异步', label: '单选异步' },
                  { id: '形状类型', label: '形状类型' },
                  { id: '样式类型', label: '样式类型' },
                  { id: '显示信息', label: '显示信息' },
                  { id: '设置禁用', label: '设置禁用' },
                  { id: '尺寸大小', label: '尺寸大小' },
                  { id: 'API', label: 'API' },
                  { id: 'Checker Props', label: 'Checker Props' },
                  { id: 'CheckerItem Props', label: 'CheckerItem Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Checkbox 复选框',
                path: '/checkbox',
                anchors: [
                  { id: '复选框', label: '复选框' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '尺寸大小', label: '尺寸大小' },
                  { id: '风格样式', label: '风格样式' },
                  { id: '禁用状态', label: '禁用状态' },
                  { id: '阻止事件冒泡', label: '阻止事件冒泡' },
                  { id: 'API', label: 'API' },
                  { id: 'Checkbox Props', label: 'Checkbox Props' },
                  { id: 'CheckboxGroup Props', label: 'CheckboxGroup Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Checkbox Events', label: 'Checkbox Events' },
                  { id: 'CheckboxGroup Events', label: 'CheckboxGroup Events' },
                  { id: '复选框组', label: '复选框组' },
                  { id: '基础用法', label: '基础用法' },
                  { id: 'API', label: 'API' },
                  { id: 'Checker Props', label: 'Checker Props' },
                  { id: 'CheckerItem Props', label: 'CheckerItem Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Field 输入框',
                path: '/field',
                anchors: [
                  { id: '输入框', label: '输入框' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '无边框样式', label: '无边框样式' },
                  { id: '输入域', label: '输入域' },
                  { id: '标题/单位用法', label: '标题/单位用法' },
                  { id: '关闭用法', label: '关闭用法' },
                  { id: '显示字数', label: '显示字数' },
                  { id: '显示字数配合 byte', label: '显示字数配合 byte' },
                  { id: '字数计算', label: '字数计算' },
                  { id: '禁用用法', label: '禁用用法' },
                  { id: '只读用法', label: '只读用法' },
                  { id: '尺寸大小', label: '尺寸大小' },
                  { id: '错误提示', label: '错误提示' },
                  { id: '插槽', label: '插槽' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: '方法', label: '方法' },
                  { id: '作用域插槽', label: '作用域插槽' },
                ],
              },
              {
                label: 'Stepper 步进器',
                path: '/stepper',
                anchors: [
                  { id: '步进器', label: '步进器' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Slider 滑块',
                path: '/slider',
                anchors: [
                  { id: '滑块', label: '滑块' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '指定范围', label: '指定范围' },
                  { id: '指定步长', label: '指定步长' },
                  { id: '指定步长值', label: '指定步长值' },
                  { id: '禁用态', label: '禁用态' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Picker 选择器',
                path: '/picker',
                anchors: [
                  { id: '选择器', label: '选择器' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '多列', label: '多列' },
                  { id: '联动', label: '联动' },
                  { id: '搭配弹层使用', label: '搭配弹层使用' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Picker Events', label: 'Picker Events' },
                ],
              },
              {
                label: 'DatetimePicker 时间选择器',
                path: '/datetime-picker',
                anchors: [
                  { id: '时间选择器', label: '时间选择器' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '选择日期（年月日）', label: '选择日期（年月日）' },
                  { id: '选择完整时间', label: '选择完整时间' },
                  { id: '选择时间', label: '选择时间' },
                  { id: '搭配弹层使用', label: '搭配弹层使用' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'DatetimePicker Events', label: 'DatetimePicker Events' },
                ],
              },
              {
                label: 'Calendar 日历',
                path: '/calendar',
                anchors: [
                  { id: 'Calendar 日历', label: 'Calendar 日历' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '要求点击确认', label: '要求点击确认' },
                  { id: '范围模式下的起止时间', label: '范围模式下的起止时间' },
                  { id: '作用域插槽', label: '作用域插槽' },
                  { id: 'API', label: 'API' },
                  { id: 'Types', label: 'Types' },
                  { id: '属性', label: '属性' },
                  { id: 'Model (v-model)', label: 'Model (v-model)' },
                  { id: '事件', label: '事件' },
                  { id: '作用域插槽', label: '作用域插槽' },
                ],
              },
              {
                label: 'Cascader 多级联动单选',
                path: '/cascader',
                anchors: [
                  { id: '多级级联单选', label: '多级级联单选' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基本类型', label: '基本类型' },
                  {
                    id: '加collapse（展开三列及以上时收起第一列）',
                    label: '加collapse（展开三列及以上时收起第一列）',
                  },
                  { id: '异步加载子节点', label: '异步加载子节点' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'options', label: 'options' },
                  { id: 'selectArray', label: 'selectArray' },
                  { id: 'selectlabelArray', label: 'selectlabelArray' },
                ],
              },
              {
                label: 'Tree 树形选择',
                path: '/tree',
                anchors: [
                  { id: 'Tree 树', label: 'Tree 树' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '不完整的值', label: '不完整的值' },
                  { id: '部分选择的选项的交互行为', label: '部分选择的选项的交互行为' },
                  { id: '扁平模式', label: '扁平模式' },
                  { id: 'API', label: 'API' },
                  { id: 'Types', label: 'Types' },
                  { id: 'Model', label: 'Model' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Upload 文件上传',
                path: '/upload',
                anchors: [
                  { id: '文件上传', label: '文件上传' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基本类型', label: '基本类型' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Search 搜索框',
                path: '/search',
                anchors: [
                  { id: '搜索框', label: '搜索框' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '取消用法', label: '取消用法' },
                  { id: '圆角用法', label: '圆角用法' },
                  { id: '插槽用法', label: '插槽用法' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Slots', label: 'Slots' },
                ],
              },
            ],
          },
          {
            label: '导航组件',
            list: [
              {
                label: 'Navbar 导航栏',
                path: '/header',
                anchors: [
                  { id: '自定义头部', label: '自定义头部' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基本用法', label: '基本用法' },
                  { id: '顶部固定', label: '顶部固定' },
                  { id: '无返回按钮', label: '无返回按钮' },
                  { id: '自定义按钮', label: '自定义按钮' },
                  { id: '样式风格', label: '样式风格' },
                  { id: '高级用法', label: '高级用法' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Slots', label: 'Slots' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Tabs 标签页',
                path: '/tab',
                anchors: [
                  { id: '标签页', label: '标签页' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '异步用法', label: '异步用法' },
                  { id: '静态布局', label: '静态布局' },
                  { id: '间距用法', label: '间距用法' },
                  { id: '安全区域用法', label: '安全区域用法' },
                  { id: '下划线样式', label: '下划线样式' },
                  { id: '文字样式', label: '文字样式' },
                  { id: '无边框', label: '无边框' },
                  { id: '样式风格 及 自定义颜色', label: '样式风格 及 自定义颜色' },
                  { id: '尺寸大小', label: '尺寸大小' },
                  { id: '标签栏滚动', label: '标签栏滚动' },
                  { id: '禁用标签', label: '禁用标签' },
                  { id: '自定义标签', label: '自定义标签' },
                  { id: '切换动画', label: '切换动画' },
                  { id: '滑动切换', label: '滑动切换' },
                  { id: '滑动切换动画', label: '滑动切换动画' },
                  { id: 'API', label: 'API' },
                  { id: 'Tabs Props', label: 'Tabs Props' },
                  { id: 'Tab Props', label: 'Tab Props' },
                  { id: 'Tabs Slots', label: 'Tabs Slots' },
                  { id: 'Tab Slots', label: 'Tab Slots' },
                  { id: 'Tabs Events', label: 'Tabs Events' },
                ],
              },
              {
                label: 'Steps 步骤条',
                path: '/steps',
                anchors: [
                  { id: '按钮', label: '按钮' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '水平版', label: '水平版' },
                  { id: '垂直版', label: '垂直版' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                ],
              },
            ],
          },
          {
            label: '展示组件',
            list: [
              {
                label: 'Tag 标签',
                path: '/tag',
                anchors: [
                  { id: '标签', label: '标签' },
                  { id: '引入', label: '引入' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '类型', label: '类型' },
                  { id: '朴素', label: '朴素' },
                  { id: '圆角样式', label: '圆角样式' },
                  { id: '自定义颜色', label: '自定义颜色' },
                  { id: '标签大小', label: '标签大小' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Slots', label: 'Slots' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Badge 徽标',
                path: '/badge',
                anchors: [
                  { id: '徽标', label: '徽标' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '设置最大值', label: '设置最大值' },
                  { id: '小红点显示', label: '小红点显示' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Loading 加载显示',
                path: '/loading',
                anchors: [
                  { id: '加载显示', label: '加载显示' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '样式类型', label: '样式类型' },
                  { id: '显示文字', label: '显示文字' },
                  { id: '垂直排列', label: '垂直排列' },
                  { id: '加载图标大小', label: '加载图标大小' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Progress 进度条',
                path: '/progress',
                anchors: [
                  { id: '进度条', label: '进度条' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '样式-2 用法', label: '样式-2 用法' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                ],
              },
              {
                label: 'Swipe 轮播',
                path: '/swipe',
                anchors: [
                  { id: '轮播', label: '轮播' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '自动播放', label: '自动播放' },
                  { id: '禁用手势', label: '禁用手势' },
                  { id: '禁止循环', label: '禁止循环' },
                  { id: '指示器颜色', label: '指示器颜色' },
                  { id: '自定义指示器', label: '自定义指示器' },
                  { id: '双向绑定', label: '双向绑定' },
                  { id: 'API', label: 'API' },
                  { id: 'Swipe v-model', label: 'Swipe v-model' },
                  { id: 'Swipe Props', label: 'Swipe Props' },
                  { id: 'Swipe Events', label: 'Swipe Events' },
                  { id: 'Swipe Slots', label: 'Swipe Slots' },
                ],
              },
              {
                label: 'ImagePreview 图片预览',
                path: '/image-preview',
                anchors: [
                  { id: '图片预览', label: '图片预览' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '通过扩展方法调用', label: '通过扩展方法调用' },
                  { id: '静态方法', label: '静态方法' },
                  { id: '组件实例方法', label: '组件实例方法' },
                  { id: '关闭', label: '关闭' },
                  { id: '更多选项', label: '更多选项' },
                  { id: '作用域插槽', label: '作用域插槽' },
                  { id: '详细说明', label: '详细说明' },
                  { id: '组件调用', label: '组件调用' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Slots', label: 'Slots' },
                  { id: 'Vue extension', label: 'Vue extension' },
                  { id: 'Options', label: 'Options' },
                ],
              },
              {
                label: 'Collapse 折叠面板',
                path: '/collapse',
                anchors: [
                  { id: '折叠面板', label: '折叠面板' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '基础用法', label: '基础用法' },
                  { id: '手风琴', label: '手风琴' },
                  { id: '高级用法', label: '高级用法' },
                  { id: 'API', label: 'API' },
                  { id: 'Collapse Props', label: 'Collapse Props' },
                  { id: 'Collapse Events', label: 'Collapse Events' },
                  { id: 'CollapseItem Props', label: 'CollapseItem Props' },
                  { id: 'CollapseItem Slots', label: 'CollapseItem Slots' },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
  'en-US': {
    logo: 'https://s2.pstatp.com/cdn/expire-1-m/byted-creative-app/static/byted-logo.svg',
    navs: [
      {
        label: 'Introduction',
        path: '/intro',
        activeIcon: introIconActive,
        defaultIcon: introIcon,
      },
      {
        label: 'Quickstart',
        path: '/quickstart',
        activeIcon: quickstartIconActive,
        defaultIcon: quickstartIcon,
      },
      {
        label: 'Changelog',
        path: '/changelog',
        activeIcon: changeLogIconActive,
        defaultIcon: changeLogIcon,
      },
      {
        label: 'Theme',
        path: '/theme',
        activeIcon: themeIconActive,
        defaultIcon: themeIcon,
      },
      {
        label: 'Brand',
        path: '/brand',
        activeIcon: themeIconActive,
        defaultIcon: themeIcon,
      },
      {
        label: 'Internationalization',
        path: '/internationalization',
        activeIcon: i18nIconActive,
        defaultIcon: i18nIcon,
      },
      {
        label: 'Components',
        list: [
          {
            label: 'Basic Components',
            activeIcon: compIconActive,
            defaultIcon: compIcon,
            list: [
              {
                label: 'Button',
                path: '/button',
                anchors: [
                  { id: 'Button', label: 'Button' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Type', label: 'Type' },
                  { id: 'Plain', label: 'Plain' },
                  { id: 'Fade', label: 'Fade' },
                  { id: 'Hairline', label: 'Hairline' },
                  { id: 'Shape', label: 'Shape' },
                  { id: 'Disabled', label: 'Disabled' },
                  { id: 'Size', label: 'Size' },
                  { id: 'Text', label: 'Text' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Popup',
                path: '/popup',
                anchors: [
                  { id: 'Popup', label: 'Popup' },
                  { id: 'install', label: 'install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'append to body', label: 'append to body' },
                  { id: 'Position', label: 'Position' },
                  { id: 'Get Container', label: 'Get Container' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Cell',
                path: '/cell',
                anchors: [
                  { id: 'Cell', label: 'Cell' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Size Usage', label: 'Size Usage' },
                  { id: 'Arrow Direction', label: 'Arrow Direction' },
                  { id: 'Value Only', label: 'Value Only' },
                  { id: 'Group Title', label: 'Group Title' },
                  { id: 'Advanced Usage', label: 'Advanced Usage' },
                  { id: 'API', label: 'API' },
                  { id: 'CellGroup Props', label: 'CellGroup Props' },
                  { id: 'Cell Props', label: 'Cell Props' },
                  { id: 'Cell Events', label: 'Cell Events' },
                  { id: 'Cell Slots', label: 'Cell Slots' },
                ],
              },
              {
                label: 'Layout',
                path: '/col',
                anchors: [
                  { id: 'Layout', label: 'Layout' },
                  { id: 'Intro', label: 'Intro' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Column Spacing', label: 'Column Spacing' },
                  { id: 'Flex Layout', label: 'Flex Layout' },
                  { id: 'API', label: 'API' },
                  { id: 'Row Props', label: 'Row Props' },
                  { id: 'Col Props', label: 'Col Props' },
                ],
              },
            ],
          },
          {
            label: 'Feedback Components',
            list: [
              {
                label: 'SwipeCell',
                path: '/swipe-cell',
                anchors: [
                  { id: 'SwipeCell', label: 'SwipeCell' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Async Close', label: 'Async Close' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Slots', label: 'Slots' },
                  { id: 'Events', label: 'Events' },
                  { id: 'close Params', label: 'close Params' },
                  { id: 'Methods', label: 'Methods' },
                ],
              },
              {
                label: 'Toast',
                path: '/toast',
                anchors: [
                  { id: 'Toast', label: 'Toast' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Text', label: 'Text' },
                  { id: 'Success/Fail/Warning/Loading', label: 'Success/Fail/Warning/Loading' },
                  { id: 'Set Time', label: 'Set Time' },
                  { id: 'ForbidClick', label: 'ForbidClick' },
                  { id: 'set private function name', label: 'set private function name' },
                  { id: 'API', label: 'API' },
                  { id: 'Options', label: 'Options' },
                ],
              },
              {
                label: 'Dialog',
                path: '/message-box',
                anchors: [
                  { id: 'MessageBox', label: 'MessageBox' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Alert dialog', label: 'Alert dialog' },
                  { id: 'Confirm dialog', label: 'Confirm dialog' },
                  { id: 'Actions', label: 'Actions' },
                  { id: 'set private function name', label: 'set private function name' },
                  { id: 'Options', label: 'Options' },
                  { id: 'Dialog', label: 'Dialog' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic', label: 'Basic' },
                  { id: 'Asnyc Close', label: 'Asnyc Close' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Slots', label: 'Slots' },
                ],
              },
              {
                label: 'NoticeBar',
                path: '/notice-bar',
                anchors: [
                  { id: 'NoticeBar', label: 'NoticeBar' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Close Usage', label: 'Close Usage' },
                  { id: 'Ellipsis Usage', label: 'Ellipsis Usage' },
                  { id: 'Style Usage', label: 'Style Usage' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Slots', label: 'Slots' },
                ],
              },
              {
                label: 'ActionSheet',
                path: '/action-sheet',
                anchors: [
                  { id: 'ActionSheet', label: 'ActionSheet' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Options Status', label: 'Options Status' },
                  { id: 'Cancel Usage', label: 'Cancel Usage' },
                  { id: 'Title Usage', label: 'Title Usage' },
                  { id: 'Extra slot', label: 'Extra slot' },
                  { id: 'API', label: 'API' },
                  { id: 'Types', label: 'Types' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Action', label: 'Action' },
                  { id: 'Scoped Slots', label: 'Scoped Slots' },
                ],
              },
              {
                label: 'Dropdown',
                path: '/dropdown',
                anchors: [
                  { id: 'Dropdown', label: 'Dropdown' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Expand Direction', label: 'Expand Direction' },
                  { id: 'Disabled', label: 'Disabled' },
                  { id: 'Custom Content', label: 'Custom Content' },
                  { id: 'Title Solt', label: 'Title Solt' },
                  { id: 'API', label: 'API' },
                  { id: 'Dropdown Props', label: 'Dropdown Props' },
                  { id: 'DropdownItem Props', label: 'DropdownItem Props' },
                  { id: 'DropdownItem Events', label: 'DropdownItem Events' },
                  { id: 'DropdownItem Slots', label: 'DropdownItem Slots' },
                  { id: 'Methods', label: 'Methods' },
                  { id: 'Option', label: 'Option' },
                ],
              },
              {
                label: 'Refresh',
                path: '/pull-refresh',
                anchors: [
                  { id: 'PullRefresh', label: 'PullRefresh' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Slots', label: 'Slots' },
                ],
              },
            ],
          },
          {
            label: 'Form Components',
            list: [
              {
                label: 'Switch',
                path: '/switch',
                anchors: [
                  { id: 'switch', label: 'switch' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'disabled', label: 'disabled' },
                  { id: 'Size Usage', label: 'Size Usage' },
                  { id: 'controlled', label: 'controlled' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Radio',
                path: '/radio',
                anchors: [
                  { id: 'Radio', label: 'Radio' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Style Usage', label: 'Style Usage' },
                  { id: 'Size Usage', label: 'Size Usage' },
                  { id: 'Disabled', label: 'Disabled' },
                  { id: 'Async Usage', label: 'Async Usage' },
                  { id: 'API', label: 'API' },
                  { id: 'Radio Props', label: 'Radio Props' },
                  { id: 'RadioGroup Props', label: 'RadioGroup Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'RadioGroup Events', label: 'RadioGroup Events' },
                  { id: 'checker', label: 'checker' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Type Radio', label: 'Type Radio' },
                  { id: 'Radio Async', label: 'Radio Async' },
                  { id: 'Basic Scope', label: 'Basic Scope' },
                  { id: 'Basic Style', label: 'Basic Style' },
                  { id: 'Show Info', label: 'Show Info' },
                  { id: 'Disabled', label: 'Disabled' },
                  { id: 'Set Size', label: 'Set Size' },
                  { id: 'API', label: 'API' },
                  { id: 'Checker Props', label: 'Checker Props' },
                  { id: 'CheckerItem Props', label: 'CheckerItem Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Checkbox',
                path: '/checkbox',
                anchors: [
                  { id: 'Checkbox', label: 'Checkbox' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Size Usage', label: 'Size Usage' },
                  { id: 'Style Usage', label: 'Style Usage' },
                  { id: 'Disabled', label: 'Disabled' },
                  { id: 'StopPropagation', label: 'StopPropagation' },
                  { id: 'API', label: 'API' },
                  { id: 'Checkbox Props', label: 'Checkbox Props' },
                  { id: 'CheckboxGroup Props', label: 'CheckboxGroup Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Checkbox Events', label: 'Checkbox Events' },
                  { id: 'CheckboxGroup Events', label: 'CheckboxGroup Events' },
                  { id: '复选框组', label: '复选框组' },
                  { id: '基础用法', label: '基础用法' },
                  { id: 'API', label: 'API' },
                  { id: 'Checker Props', label: 'Checker Props' },
                  { id: 'CheckerItem Props', label: 'CheckerItem Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Field',
                path: '/field',
                anchors: [
                  { id: 'Field', label: 'Field' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'No Border Style', label: 'No Border Style' },
                  { id: 'label/unit Usage', label: 'label/unit Usage' },
                  { id: 'Close Usage', label: 'Close Usage' },
                  { id: 'Word Limit', label: 'Word Limit' },
                  { id: 'Word Limit Width Byte', label: 'Word Limit Width Byte' },
                  { id: 'Length Calculation', label: 'Length Calculation' },
                  { id: 'Disabled Usage', label: 'Disabled Usage' },
                  { id: 'Readonly Usage', label: 'Readonly Usage' },
                  { id: 'Size', label: 'Size' },
                  { id: 'ErrorText', label: 'ErrorText' },
                  { id: 'Slots', label: 'Slots' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Methods', label: 'Methods' },
                  { id: 'Scoped slots', label: 'Scoped slots' },
                ],
              },
              {
                label: 'Stepper',
                path: '/stepper',
                anchors: [
                  { id: 'Stepper', label: 'Stepper' },
                  { id: 'install', label: 'install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'basic usage', label: 'basic usage' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Slider',
                path: '/slider',
                anchors: [
                  { id: 'Slider', label: 'Slider' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Range Usage', label: 'Range Usage' },
                  { id: 'Step Usage', label: 'Step Usage' },
                  { id: '指定步长值', label: '指定步长值' },
                  { id: 'Disabled Usage', label: 'Disabled Usage' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Picker',
                path: '/picker',
                anchors: [
                  { id: 'Picker', label: 'Picker' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'multiple', label: 'multiple' },
                  { id: 'cascade', label: 'cascade' },
                  { id: 'With Popup', label: 'With Popup' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Picker Events', label: 'Picker Events' },
                ],
              },
              {
                label: 'DatetimePicker',
                path: '/datetime-picker',
                anchors: [
                  { id: 'DatetimePicker', label: 'DatetimePicker' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Choose Date(Year-Month-Day)', label: 'Choose Date(Year-Month-Day)' },
                  { id: 'Choose Datetime', label: 'Choose Datetime' },
                  { id: 'Choose Time', label: 'Choose Time' },
                  { id: 'With Popup', label: 'With Popup' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'DatetimePicker Events', label: 'DatetimePicker Events' },
                ],
              },
              {
                label: 'Calendar',
                path: '/calendar',
                anchors: [
                  { id: 'Calendar', label: 'Calendar' },
                  { id: 'Installation', label: 'Installation' },
                  { id: 'Examples', label: 'Examples' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Require to click confirm', label: 'Require to click confirm' },
                  {
                    id: 'The start and end time in range mode',
                    label: 'The start and end time in range mode',
                  },
                  { id: 'Scoped Slots', label: 'Scoped Slots' },
                  { id: 'API', label: 'API' },
                  { id: 'Types', label: 'Types' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Model (v-model)', label: 'Model (v-model)' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Scoped Slots', label: 'Scoped Slots' },
                ],
              },
              {
                label: 'Cascader',
                path: '/cascader',
                anchors: [
                  { id: 'cascader', label: 'cascader' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Type', label: 'Type' },
                  { id: 'add collapse', label: 'add collapse' },
                  { id: 'async loading children', label: 'async loading children' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'options', label: 'options' },
                  { id: 'selectArray', label: 'selectArray' },
                  { id: 'selectlabelArray', label: 'selectlabelArray' },
                ],
              },
              {
                label: 'Tree',
                path: '/tree',
                anchors: [
                  { id: 'Tree', label: 'Tree' },
                  { id: 'Installation', label: 'Installation' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Incomplete Values', label: 'Incomplete Values' },
                  {
                    id: 'Interaction behavior of partially selected options',
                    label: 'Interaction behavior of partially selected options',
                  },
                  { id: 'Flat Mode', label: 'Flat Mode' },
                  { id: 'API', label: 'API' },
                  { id: 'Types', label: 'Types' },
                  { id: 'Model', label: 'Model' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Upload',
                path: '/upload',
                anchors: [
                  { id: 'Upload', label: 'Upload' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Default', label: 'Default' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Search',
                path: '/search',
                anchors: [
                  { id: 'Search', label: 'Search' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Cancel Usage', label: 'Cancel Usage' },
                  { id: 'border-radius Usage', label: 'border-radius Usage' },
                  { id: 'Slots Usage', label: 'Slots Usage' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Slots', label: 'Slots' },
                ],
              },
            ],
          },
          {
            label: 'Navigation Components',
            list: [
              {
                label: 'Navbar',
                path: '/header',
                anchors: [
                  { id: 'Header', label: 'Header' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Fixed header', label: 'Fixed header' },
                  { id: 'No button', label: 'No button' },
                  { id: 'Custom button', label: 'Custom button' },
                  { id: 'Style', label: 'Style' },
                  { id: 'Advanced Usage', label: 'Advanced Usage' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Slots', label: 'Slots' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Tab',
                path: '/tab',
                anchors: [
                  { id: 'Tab', label: 'Tab' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Ansyc Usage', label: 'Ansyc Usage' },
                  { id: 'Static Layout', label: 'Static Layout' },
                  { id: 'gutter Usage', label: 'gutter Usage' },
                  { id: 'safe-area-inset Usage', label: 'safe-area-inset Usage' },
                  { id: 'Underline Style', label: 'Underline Style' },
                  { id: 'Text Style', label: 'Text Style' },
                  { id: 'No Border', label: 'No Border' },
                  { id: 'Style And Custom Color', label: 'Style And Custom Color' },
                  { id: 'Size Usage', label: 'Size Usage' },
                  { id: 'Tab Bar Scroll', label: 'Tab Bar Scroll' },
                  { id: 'Disabled Tab', label: 'Disabled Tab' },
                  { id: 'Custom Tab', label: 'Custom Tab' },
                  { id: 'Animated Usage', label: 'Animated Usage' },
                  { id: 'Swipeable Usage', label: 'Swipeable Usage' },
                  { id: 'Touchable Usage', label: 'Touchable Usage' },
                  { id: 'API', label: 'API' },
                  { id: 'Tabs Props', label: 'Tabs Props' },
                  { id: 'Tab Props', label: 'Tab Props' },
                  { id: 'Tabs Slots', label: 'Tabs Slots' },
                  { id: 'Tab Slots', label: 'Tab Slots' },
                  { id: 'Tabs Events', label: 'Tabs Events' },
                ],
              },
              {
                label: 'Steps',
                path: '/steps',
                anchors: [
                  { id: '按钮', label: '按钮' },
                  { id: '安装', label: '安装' },
                  { id: '代码演示', label: '代码演示' },
                  { id: '水平版', label: '水平版' },
                  { id: '垂直版', label: '垂直版' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                ],
              },
            ],
          },
          {
            label: 'Display Components',
            list: [
              {
                label: 'Tag',
                path: '/tag',
                anchors: [
                  { id: 'Tag', label: 'Tag' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Type', label: 'Type' },
                  { id: 'Plain', label: 'Plain' },
                  { id: 'Round', label: 'Round' },
                  { id: 'Custom color', label: 'Custom color' },
                  { id: 'Size', label: 'Size' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Slots', label: 'Slots' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Badge',
                path: '/badge',
                anchors: [
                  { id: 'Badge', label: 'Badge' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic', label: 'Basic' },
                  { id: 'Set max', label: 'Set max' },
                  { id: 'Dot', label: 'Dot' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Loading',
                path: '/loading',
                anchors: [
                  { id: 'Loading', label: 'Loading' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic', label: 'Basic' },
                  { id: 'Style', label: 'Style' },
                  { id: 'Words', label: 'Words' },
                  { id: 'Vertical', label: 'Vertical' },
                  { id: 'Icon Size', label: 'Icon Size' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                ],
              },
              {
                label: 'Progress',
                path: '/progress',
                anchors: [
                  { id: 'Progress', label: 'Progress' },
                  { id: 'install', label: 'install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'theme-2 Usage', label: 'theme-2 Usage' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                ],
              },
              {
                label: 'Swipe',
                path: '/swipe',
                anchors: [
                  { id: 'Swipe', label: 'Swipe' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic', label: 'Basic' },
                  { id: 'autoplay', label: 'autoplay' },
                  { id: 'Forbid tap', label: 'Forbid tap' },
                  { id: 'Forbid loop', label: 'Forbid loop' },
                  { id: 'Custom Indicator Color', label: 'Custom Indicator Color' },
                  { id: 'Custom Indicator', label: 'Custom Indicator' },
                  {
                    id: 'Controlled Mode (Two-way Binding)',
                    label: 'Controlled Mode (Two-way Binding)',
                  },
                  { id: 'API', label: 'API' },
                  { id: 'Swipe v-model', label: 'Swipe v-model' },
                  { id: 'Swipe Props', label: 'Swipe Props' },
                  { id: 'Swipe Events', label: 'Swipe Events' },
                  { id: 'Swipe Slots', label: 'Swipe Slots' },
                ],
              },
              {
                label: 'ImagePreview',
                path: '/image-preview',
                anchors: [
                  { id: 'Image Preview', label: 'Image Preview' },
                  { id: 'Installation', label: 'Installation' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Use via extension methods', label: 'Use via extension methods' },
                  {
                    id: 'Static method Vue.$imagePreview(options)',
                    label: 'Static method Vue.$imagePreview(options)',
                  },
                  {
                    id: 'Component instance method Vue.prototype.$imagePreview(options)',
                    label: 'Component instance method Vue.prototype.$imagePreview(options)',
                  },
                  { id: 'Closing', label: 'Closing' },
                  { id: 'More options', label: 'More options' },
                  { id: 'API', label: 'API' },
                  { id: 'Props', label: 'Props' },
                  { id: 'Events', label: 'Events' },
                  { id: 'Slots', label: 'Slots' },
                  { id: 'Vue extension', label: 'Vue extension' },
                  { id: 'Options', label: 'Options' },
                ],
              },
              {
                label: 'Collapse',
                path: '/collapse',
                anchors: [
                  { id: 'Collapse', label: 'Collapse' },
                  { id: 'Install', label: 'Install' },
                  { id: 'Usage', label: 'Usage' },
                  { id: 'Basic Usage', label: 'Basic Usage' },
                  { id: 'Accordion Usage', label: 'Accordion Usage' },
                  { id: 'Advanced Usage', label: 'Advanced Usage' },
                  { id: 'API', label: 'API' },
                  { id: 'Collapse Props', label: 'Collapse Props' },
                  { id: 'Collapse Events', label: 'Collapse Events' },
                  { id: 'CollapseItem Props', label: 'CollapseItem Props' },
                  { id: 'CollapseItem Slots', label: 'CollapseItem Slots' },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
};

export { Config, NavsItem, TypeConfig };

export default config;
