"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file aiming 瞄准
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('aiming', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(4.000000, 4.000000)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth
    }
  }, [h("g", [h("circle", {
    "attrs": {
      "cx": "20",
      "cy": "20",
      "r": "20"
    }
  }), h("path", {
    "attrs": {
      "d": "M20,7 L20,1"
    }
  }), h("path", {
    "attrs": {
      "d": "M20,33 L20,39"
    }
  }), h("path", {
    "attrs": {
      "d": "M1,20 L7,20"
    }
  }), h("path", {
    "attrs": {
      "d": "M32,20 L38,20"
    }
  })])])])]);
});

exports.default = _default;