"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file align-text-middle 文字中间对齐
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('align-text-middle', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(6.000000, 3.000000)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(12.000000, 27.000000)"
    }
  }, [h("polyline", {
    "attrs": {
      "points": "0 6 6 0 12 6"
    }
  }), h("path", {
    "attrs": {
      "d": "M6,1 L6,14"
    }
  })]), h("g", {
    "attrs": {
      "transform": "translate(18.000000, 7.500000) scale(1, -1) translate(-18.000000, -7.500000) translate(12.000000, 0.000000)"
    }
  }, [h("polyline", {
    "attrs": {
      "points": "0 6 6 0 12 6"
    }
  }), h("path", {
    "attrs": {
      "d": "M6,1 L6,14"
    }
  })]), h("path", {
    "attrs": {
      "d": "M0,21 L36,21"
    }
  })])])]);
});

exports.default = _default;