"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file anchor 锚点
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('anchor', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(4.000000, 4.000000)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth
    }
  }, [h("path", {
    "attrs": {
      "d": "M32,36 L28,36 L20,36 L12,36 L8,36 M4,32 L4,28 L4,20 L4,12 L4,8 M8,4 L12,4 L20,4 L28,4 L32,4 M36,8 L36,12 L36,20 L36,28 L36,32",
      "stroke-linecap": props.strokeLinecap
    }
  }), h("rect", {
    "attrs": {
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "x": "32",
      "y": "0",
      "width": "8",
      "height": "8",
      "rx": "2"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "x": "0",
      "y": "0",
      "width": "8",
      "height": "8",
      "rx": "2"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "x": "32",
      "y": "32",
      "width": "8",
      "height": "8",
      "rx": "2"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "x": "0",
      "y": "32",
      "width": "8",
      "height": "8",
      "rx": "2"
    }
  })])])]);
});

exports.default = _default;