"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file arrow-right-up 箭头右上
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('arrow-right-up', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("g", {
    "attrs": {
      "transform": "translate(11.275537, 10.000000)",
      "stroke": props.outStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "stroke-width": props.strokeWidth
    }
  }, [h("polyline", {
    "attrs": {
      "points": "7.72446285 1 25.7244629 1 25.7244629 19"
    }
  }), h("path", {
    "attrs": {
      "d": "M30.9930816,14.0807954 L-5,13.3750487",
      "transform": "translate(12.996541, 13.727922) rotate(133.876697) translate(-12.996541, -13.727922) "
    }
  })])])])]);
});

exports.default = _default;