"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file block-seven 俄罗斯方块
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('block-seven', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("path", {
    "attrs": {
      "d": "M6 18H18V30H6V18Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M18 6H30V18H18V6Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M18 18H30V30H18V18Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M30 18H42V30H30V18Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M18 30H30V42H18V30Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M18 18H6V30H18M18 18V30M18 18H30M18 18V6H30V18M18 30H30M18 30V42H30V30M30 18V30M30 18H42V30H30",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;