"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file block-ten 俄罗斯方块
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('block-ten', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("path", {
    "attrs": {
      "d": "M12 6H24V18H12V6Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M24 6H36V18H24V6Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M12 18H24V30H12V18Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M12 30H24V42H12V30Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M24 6H12V18M24 6V18M24 6H36V18H24M24 18H12M24 18V30M12 18V30M24 30H12M24 30V42H12V30",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;