"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file block-four 俄罗斯方块
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('block-four', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("path", {
    "attrs": {
      "d": "M6 12H18V24H6V12Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M18 12H30V24H18V12Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M18 24H30V36H18V24Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M30 12H42V24H30V12Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M18 12H6V24H18M18 12V24M18 12H30M18 24H30M18 24V36H30V24M30 12V24M30 12H42V24H30",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;