"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file book-open 书籍-打开
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('book-open', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("g", {
    "attrs": {
      "transform": "translate(4.000000, 7.000000)",
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke": props.outStrokeColor,
      "stroke-linejoin": props.strokeLinejoin,
      "stroke-width": props.strokeWidth
    }
  }, [h("path", {
    "attrs": {
      "d": "M0,2.27373675e-13 L12,2.27373675e-13 C16.418278,2.27373675e-13 20,3.581722 20,8 L20,36 C20,32.6862915 17.3137085,30 14,30 L0,30 L0,2.27373675e-13 Z"
    }
  }), h("path", {
    "attrs": {
      "d": "M40,0 L28,0 C23.581722,0 20,3.581722 20,8 L20,36 C20,32.6862915 22.6862915,30 26,30 L40,30 L40,0 Z"
    }
  })])])])]);
});

exports.default = _default;