"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file browser-safari 浏览器-safari
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('browser-safari', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(4.000000, 4.000000)"
    }
  }, [h("circle", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin,
      "cx": "20",
      "cy": "20",
      "r": "20"
    }
  }), h("polygon", {
    "attrs": {
      "stroke": props.innerStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.innerFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin,
      "points": "11 29 15.5 15.5 29 11 24.5 24.5"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "cx": "20",
      "cy": "20",
      "r": "2"
    }
  })])])]);
});

exports.default = _default;