"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file city 城市
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('city', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("path", {
    "attrs": {
      "d": "M4,42 L44,42",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("rect", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin,
      "x": "8",
      "y": "26",
      "width": "8",
      "height": "16",
      "rx": "2"
    }
  }), h("path", {
    "attrs": {
      "d": "M12,34 L13,34",
      "stroke": props.innerStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("rect", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin,
      "x": "16",
      "y": "4",
      "width": "24",
      "height": "38",
      "rx": "2"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "22",
      "y": "10",
      "width": "4",
      "height": "4"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "30",
      "y": "10",
      "width": "4",
      "height": "4"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "22",
      "y": "17",
      "width": "4",
      "height": "4"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "30",
      "y": "17",
      "width": "4",
      "height": "4"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "30",
      "y": "24",
      "width": "4",
      "height": "4"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "30",
      "y": "31",
      "width": "4",
      "height": "4"
    }
  })])])]);
});

exports.default = _default;