"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file clothes-pants-sweat 运动裤
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('clothes-pants-sweat', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("path", {
    "attrs": {
      "d": "M33 38L24 19L15 38H14L13 44H7V38H6L10 4H17H24H31H38L42 38H41V44H35L34 38H33Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M15 38L24 19L33 38H34M15 38H6M15 38H14L13 44H7V38H6M6 38L10 4H17H24M24 4L20 11.5M24 4H31H38L42 38H41M24 4L27 11M34 38L35 44H41V38M34 38H41",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;