"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file column-small 声音-小
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('column-small', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("path", {
    "attrs": {
      "d": "M24,6 L24,42 C19.3333333,42 15.2661751,38.9463725 11.7985252,32.8391176 L6,32.8391176 C4.8954305,32.8391176 4,31.9436871 4,30.8391176 L4,17.0107694 C4,15.9061999 4.8954305,15.0107694 6,15.0107694 L11.7985252,15.0107694 C15.2661751,9.00358979 19.3333333,6 24,6 Z",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("path", {
    "attrs": {
      "d": "M32,15 L32,15 C32.6232413,15.5565175 33.1881439,16.1797339 33.684083,16.8587755 C35.1386691,18.8504 36,21.3222583 36,24 C36,26.6545336 35.1535348,29.1067371 33.7217701,31.0893319 C33.2168263,31.7885382 32.6390843,32.4293355 32,33",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })])])]);
});

exports.default = _default;