"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file cube 魔方
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('cube', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("path", {
    "attrs": {
      "d": "M24.0002 4L32.6605 9L41.3207 14V24V34L32.6605 39L24.0002 44L15.3399 39L6.67969 34V24V14L15.3399 9L24.0002 4Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M41.3207 14L32.6605 19M41.3207 14V24M41.3207 14L32.6605 9M24.0002 44L32.6605 39M24.0002 44L15.3399 39M24.0002 44V34M6.67969 14L15.3399 9M6.67969 14L15.3399 19M6.67969 14V24M24.0002 24L32.6605 19M24.0002 24L15.3399 19M24.0002 24V34M32.6605 19L15.3399 9M32.6605 19V39M15.3399 9L24.0002 4L32.6605 9M32.6605 39L41.3207 34V24M15.3399 39L6.67969 34V24M15.3399 39V19M15.3399 19L32.6605 9M6.67969 24L24.0002 34M24.0002 34L41.3207 24",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;