"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file cutting 裁切
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('cutting', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(6.000000, 5.000000)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(0.000000, 0.021632)"
    }
  }, [h("polyline", {
    "attrs": {
      "points": "0 4.97836848 32 4.97836848 32 36.9783685"
    }
  }), h("path", {
    "attrs": {
      "d": "M20.4664367,-6 L20.4664367,39.0238636",
      "transform": "translate(20.466437, 16.511932) rotate(-135.000000) translate(-20.466437, -16.511932) "
    }
  }), h("polyline", {
    "attrs": {
      "transform": "translate(20.000000, 16.978368) scale(-1, -1) translate(-20.000000, -16.978368) ",
      "points": "4 0.978368479 36 0.978368479 36 32.9783685"
    }
  })])])])]);
});

exports.default = _default;