"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file download-three 下载3
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('download-three', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("rect", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin,
      "x": "6",
      "y": "6",
      "width": "36",
      "height": "36",
      "rx": "3"
    }
  }), h("g", {
    "attrs": {
      "transform": "translate(16.000000, 19.000000)",
      "stroke": props.innerStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "stroke-width": props.strokeWidth
    }
  }, [h("polyline", {
    "attrs": {
      "transform": "translate(8.000000, 13.000000) rotate(90.000000) translate(-8.000000, -13.000000) ",
      "points": "4 5 12 13 4 21"
    }
  }), h("path", {
    "attrs": {
      "d": "M-0.5,8.5 L15,8.5",
      "transform": "translate(7.500000, 9.000000) rotate(90.000000) translate(-7.500000, -9.000000) "
    }
  })]), h("path", {
    "attrs": {
      "d": "M16,14 L32,14",
      "stroke": props.innerStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })])])]);
});

exports.default = _default;