"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file edit-one 编辑1
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('edit-one', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("g", {
    "attrs": {
      "transform": "translate(7.000000, 4.000000)",
      "stroke": props.outStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "stroke-width": props.strokeWidth
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(16.000000, 20.000000) scale(1, -1) translate(-16.000000, -20.000000) "
    }
  }, [h("path", {
    "attrs": {
      "d": "M22,40 L2,40 C0.8954305,40 0,39.1045695 0,38 L0,2 C0,0.8954305 0.8954305,0 2,0 L30,0 C31.1045695,0 32,0.8954305 32,2 L32,23.9954303",
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("path", {
    "attrs": {
      "d": "M6,26 L14,26"
    }
  }), h("path", {
    "attrs": {
      "d": "M6,16 L18,16"
    }
  })]), h("path", {
    "attrs": {
      "d": "M33.9992828,2.00078247 L22.0045933,13.9956182",
      "stroke-linejoin": props.strokeLinejoin
    }
  })])])])]);
});

exports.default = _default;