"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file equal-ratio 等比
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('equal-ratio', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("g", {
    "attrs": {
      "transform": "translate(6.000000, 6.000000)"
    }
  }, [h("g", {
    "attrs": {
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke": props.outStrokeColor,
      "stroke-linejoin": props.strokeLinejoin,
      "stroke-width": props.strokeWidth
    }
  }, [h("rect", {
    "attrs": {
      "x": "0",
      "y": "0",
      "width": "36",
      "height": "36",
      "rx": "3"
    }
  })]), h("circle", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "cx": "18",
      "cy": "14",
      "r": "2.5"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "cx": "18",
      "cy": "22",
      "r": "2.5"
    }
  }), h("path", {
    "attrs": {
      "d": "M9.5,11 L9.5,25",
      "stroke": props.innerStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("path", {
    "attrs": {
      "d": "M26.5,11 L26.5,25",
      "stroke": props.innerStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })])])])]);
});

exports.default = _default;