"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file finance 金融
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('finance', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(4.000000, 4.000000)",
      "stroke-width": props.strokeWidth
    }
  }, [h("circle", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "cx": "20",
      "cy": "20",
      "r": "20"
    }
  }), h("g", {
    "attrs": {
      "transform": "translate(14.000000, 11.000000)",
      "stroke": props.innerStrokeColor,
      "stroke-linecap": props.strokeLinecap
    }
  }, [h("path", {
    "attrs": {
      "d": "M0,7 L12,7"
    }
  }), h("path", {
    "attrs": {
      "d": "M0,13 L12,13"
    }
  }), h("path", {
    "attrs": {
      "d": "M6.00833333,7 L6.00833333,19"
    }
  }), h("polyline", {
    "attrs": {
      "transform": "translate(6.000000, 3.000000) rotate(90.000000) translate(-6.000000, -3.000000) ",
      "points": "3 -3 9 3 3 9"
    }
  })])])])]);
});

exports.default = _default;