"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file fireworks 礼花
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('fireworks', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(6.000000, 2.000000)"
    }
  }, [h("polygon", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin,
      "points": "0 40 8.67409249 15.2640024 25 32.0384615"
    }
  }), h("path", {
    "attrs": {
      "d": "M17,17 L22,12 C24.6666667,9.33333333 25,7 23,5",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("path", {
    "attrs": {
      "d": "M23,23 L28,18 C31.3333333,14.6666667 34.6666667,14.6666667 38,18",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "14",
      "cy": "3",
      "r": "2"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "36",
      "cy": "2",
      "r": "2"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "36",
      "cy": "25",
      "r": "2"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "33",
      "cy": "34",
      "r": "2"
    }
  })])])]);
});

exports.default = _default;