"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file four-point-connection 四点连接
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('four-point-connection', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("path", {
    "attrs": {
      "d": "M20 4H28V8V12H20V8V4Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M20 36H28V40V44H20V40V36Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M4 20H8H12V28H8H4V20Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M36 20H40H44V28H40H36V20Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M40 20H36V28H40M40 20H44V28H40M40 20V8H28M28 8V4H20V8M28 8V12H20V8M20 8H8V20M8 20H4V28H8M8 20H12V28H8M8 28V40H20M20 40V44H28V40M20 40V36H28V40M28 40H40V28",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("path", {
    "attrs": {
      "d": "M24 18V30",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("path", {
    "attrs": {
      "d": "M18 24H30",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;