"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file geometric-flowers 几何花
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('geometric-flowers', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 52 52",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("ellipse", {
    "attrs": {
      "cx": "17.6777",
      "cy": "17.6778",
      "rx": "9",
      "ry": "16",
      "transform": "rotate(-45 17.6777 17.6778)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("ellipse", {
    "attrs": {
      "rx": "9",
      "ry": "16",
      "transform": "matrix(0.707107 0.707107 0.707107 -0.707107 17.6777 31.3784)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("ellipse", {
    "attrs": {
      "rx": "9",
      "ry": "16",
      "transform": "matrix(-0.707107 -0.707107 -0.707107 0.707107 31.3223 17.6778)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("ellipse", {
    "attrs": {
      "cx": "31.3223",
      "cy": "31.3784",
      "rx": "9",
      "ry": "16",
      "transform": "rotate(135 31.3223 31.3784)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;