"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file h3 标题2
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('h3', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(5.000000, 7.000000)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(0.000000, 0.500000)"
    }
  }, [h("path", {
    "attrs": {
      "d": "M1,0.5 L1,32.5"
    }
  }), h("path", {
    "attrs": {
      "d": "M19,0.5 L19,32.5"
    }
  }), h("path", {
    "attrs": {
      "d": "M2,16.5 L18,16.5"
    }
  })]), h("path", {
    "attrs": {
      "d": "M27,12 L37,12 L29.8571429,20.4 C33.4285714,20.4 37,23.9 37,27.4 C37,30.9 34.1428571,33 32,33 C29.6190476,33 27.952381,32.3 27,30.9"
    }
  })])])]);
});

exports.default = _default;