"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file i-mac 苹果电脑iMac
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('i-mac', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("polygon", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin,
      "points": "4 6 44 6 44 30 4 30"
    }
  }), h("polyline", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "points": "44 30 44 36 4 36 4 30 4 30"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "10",
      "y": "19",
      "width": "4",
      "height": "4",
      "rx": "0.909090909"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "10",
      "y": "12",
      "width": "4",
      "height": "4",
      "rx": "0.909090909"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "18",
      "y": "19",
      "width": "4",
      "height": "4",
      "rx": "0.909090909"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "18",
      "y": "12",
      "width": "4",
      "height": "4",
      "rx": "0.909090909"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "26",
      "y": "19",
      "width": "4",
      "height": "4",
      "rx": "0.909090909"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "26",
      "y": "12",
      "width": "4",
      "height": "4",
      "rx": "0.909090909"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "34",
      "y": "12",
      "width": "4",
      "height": "4",
      "rx": "0.909090909"
    }
  }), h("polyline", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "points": "20.8461538 36 16 42 32 42 27.1538462 36"
    }
  })])])]);
});

exports.default = _default;