"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file left-small-down 左下-小
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('left-small-down', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("g", {
    "attrs": {
      "transform": "translate(14.479185, 15.000000)",
      "stroke": props.outStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "stroke-width": props.strokeWidth
    }
  }, [h("path", {
    "attrs": {
      "d": "M21.0416306,9.5 L-3,9.5",
      "transform": "translate(9.020815, 9.500000) rotate(-225.000000) translate(-9.020815, -9.500000) "
    }
  }), h("polyline", {
    "attrs": {
      "transform": "translate(9.520815, 9.000000) rotate(-180.000000) translate(-9.520815, -9.000000) ",
      "points": "0.52081528 0 18.5208153 0 18.5208153 18"
    }
  })])])])]);
});

exports.default = _default;