"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file lifebuoy 救生圈
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('lifebuoy', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("path", {
    "attrs": {
      "fill-rule": "evenodd",
      "clip-rule": "evenodd",
      "d": "M38.1421 38.1421C45.9526 30.3316 45.9526 17.6684 38.1421 9.85786C30.3316 2.04738 17.6684 2.04738 9.85786 9.85786C2.04738 17.6684 2.04738 30.3316 9.85786 38.1421C17.6684 45.9526 30.3316 45.9526 38.1421 38.1421ZM32.4853 15.5147C37.1716 20.201 37.1716 27.799 32.4853 32.4853C27.799 37.1716 20.201 37.1716 15.5147 32.4853C10.8284 27.799 10.8284 20.201 15.5147 15.5147C20.201 10.8284 27.799 10.8284 32.4853 15.5147Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M38.1421 9.85786C45.9526 17.6684 45.9526 30.3316 38.1421 38.1421M38.1421 9.85786C30.3316 2.04738 17.6684 2.04738 9.85786 9.85786M38.1421 9.85786L32.4853 15.5147M38.1421 38.1421C30.3316 45.9526 17.6684 45.9526 9.85786 38.1421M38.1421 38.1421L32.4853 32.4853M9.85786 38.1421C2.04738 30.3316 2.04738 17.6684 9.85786 9.85786M9.85786 38.1421L15.5147 32.4853M9.85786 9.85786L15.5147 15.5147M32.4853 15.5147C37.1716 20.201 37.1716 27.799 32.4853 32.4853M32.4853 15.5147C27.799 10.8284 20.201 10.8284 15.5147 15.5147M32.4853 32.4853C27.799 37.1716 20.201 37.1716 15.5147 32.4853M15.5147 32.4853C10.8284 27.799 10.8284 20.201 15.5147 15.5147",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;