"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file login 进入
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('login', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(6.000000, 6.000000)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(18.000000, 18.000000) rotate(90.000000) translate(-18.000000, -18.000000) "
    }
  }, [h("polyline", {
    "attrs": {
      "points": "2.49800181e-16 18.0083363 2.49800181e-16 36 36 36 36 18"
    }
  }), h("g", {
    "attrs": {
      "transform": "translate(18.000000, 13.000000) rotate(90.000000) translate(-18.000000, -13.000000) translate(5.000000, 4.000000)"
    }
  }, [h("polyline", {
    "attrs": {
      "points": "17 -1.23094459e-13 26 9 17 18"
    }
  }), h("path", {
    "attrs": {
      "d": "M1.70530257e-13,9.00833628 L26,9.00833628"
    }
  })])])])])]);
});

exports.default = _default;