"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file module-search 搜索
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('module-search', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 64 64",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("path", {
    "attrs": {
      "d": "M60 43V21H4V43H60Z",
      "fill": props.outFillColor,
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("path", {
    "attrs": {
      "d": "M52 31C52 32.1046 51.5523 33.1046 50.8284 33.8284C50.1046 34.5523 49.1046 35 48 35C45.7909 35 44 33.2091 44 31C44 28.7909 45.7909 27 48 27C50.2091 27 52 28.7909 52 31Z",
      "fill": props.innerFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M54 37L50.8284 33.8284M50.8284 33.8284C51.5523 33.1046 52 32.1046 52 31C52 28.7909 50.2091 27 48 27C45.7909 27 44 28.7909 44 31C44 33.2091 45.7909 35 48 35C49.1046 35 50.1046 34.5523 50.8284 33.8284Z",
      "stroke": props.innerStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;