"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file plug 插头
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('plug', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(6.000000, 4.000000)",
      "stroke-width": props.strokeWidth
    }
  }, [h("path", {
    "attrs": {
      "d": "M0,10 L36,10 L36,20 C32,28 26,32 18,32 C10,32 4,28 0,20 L0,10 Z",
      "stroke": props.outStrokeColor,
      "fill": props.outFillColor,
      "fill-rule": "nonzero"
    }
  }), h("polyline", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "points": "27 30 26 40 10 40 9 30"
    }
  }), h("path", {
    "attrs": {
      "d": "M16,20 L20,20",
      "stroke": props.innerStrokeColor,
      "stroke-linecap": props.strokeLinecap
    }
  }), h("path", {
    "attrs": {
      "d": "M10,8 L10,0",
      "stroke": props.outStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "transform": "translate(10.000000, 4.000000) rotate(180.000000) translate(-10.000000, -4.000000) "
    }
  }), h("path", {
    "attrs": {
      "d": "M26,8 L26,0",
      "stroke": props.outStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "transform": "translate(26.000000, 4.000000) rotate(180.000000) translate(-26.000000, -4.000000) "
    }
  })])])]);
});

exports.default = _default;