"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file return 返回
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('return', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("polyline", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "transform": "translate(12.363961, 14.363961) rotate(45.000000) translate(-12.363961, -14.363961) ",
      "points": "7.86396103 9.86396103 7.86396103 18.863961 16.863961 18.863961"
    }
  }), h("path", {
    "attrs": {
      "d": "M6,14.363961 L28.1722323,14.363961 C35.3362845,14.363961 41.22076,20.0233725 41.5,27.1819805 C41.7655807,33.9904186 36.4615469,39.7250439 29.6531088,39.9906247 C29.4928928,39.9968743 29.3325702,40 29.1722323,40 L12,40",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })])])]);
});

exports.default = _default;