"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file right-c 右-圆
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('right-c', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("g", {
    "attrs": {
      "transform": "translate(4.000000, 4.000000)",
      "stroke-linejoin": props.strokeLinejoin,
      "stroke-width": props.strokeWidth
    }
  }, [h("circle", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "cx": "20",
      "cy": "20",
      "r": "20"
    }
  }), h("polyline", {
    "attrs": {
      "stroke": props.innerStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "transform": "translate(21.500000, 20.000000) scale(1, -1) translate(-21.500000, -20.000000) ",
      "points": "17 11 26 20 17 29"
    }
  })])])])]);
});

exports.default = _default;