"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file round-distortion 圆形扭曲
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('round-distortion', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("path", {
    "attrs": {
      "d": "M44 24C44 35.0457 35.0457 44 24 44C12.9543 44 4 35.0457 4 24C4 12.9543 12.9543 4 24 4C35.0457 4 44 12.9543 44 24Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M44 24C44 35.0457 35.0457 44 24 44M44 24C44 12.9543 35.0457 4 24 4M44 24C44 29.5228 39.5228 34 34 34C28.4772 34 24 29.5228 24 24M24 44C12.9543 44 4 35.0457 4 24M24 44C18.4772 44 14 39.5228 14 34C14 28.4772 18.4772 24 24 24M4 24C4 12.9543 12.9543 4 24 4M4 24C4 18.4772 8.47715 14 14 14C19.5228 14 24 18.4772 24 24M24 4C29.5228 4 34 8.47715 34 14C34 19.5228 29.5228 24 24 24",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;