"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file server 服务器
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('server', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("rect", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin,
      "x": "4",
      "y": "4",
      "width": "40",
      "height": "16"
    }
  }), h("rect", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin,
      "x": "4",
      "y": "28",
      "width": "40",
      "height": "16"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "10",
      "y": "10",
      "width": "4",
      "height": "4",
      "rx": "1"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "10",
      "y": "34",
      "width": "4",
      "height": "4",
      "rx": "1"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "18",
      "y": "10",
      "width": "4",
      "height": "4",
      "rx": "1"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.innerStrokeColor,
      "x": "18",
      "y": "34",
      "width": "4",
      "height": "4",
      "rx": "1"
    }
  })])])]);
});

exports.default = _default;