"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file shake 震动
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('shake', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(4.000000, 6.000000)",
      "stroke-width": props.strokeWidth
    }
  }, [h("polyline", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "points": "0 4 4 8.66666667 0 13.3333333 4 18 0 22.6666667 4 27.3333333 0 32"
    }
  }), h("polyline", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "transform": "translate(38.000000, 18.000000) scale(-1, 1) translate(-38.000000, -18.000000) ",
      "points": "36 4 40 8.66666667 36 13.3333333 40 18 36 22.6666667 40 27.3333333 36 32"
    }
  }), h("rect", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "x": "10",
      "y": "0",
      "width": "20",
      "height": "36"
    }
  }), h("path", {
    "attrs": {
      "d": "M18,29 L22,29",
      "stroke": props.innerStrokeColor,
      "stroke-linecap": props.strokeLinecap
    }
  })])])]);
});

exports.default = _default;