"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file skull 骷髅
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('skull', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("path", {
    "attrs": {
      "d": "M11.2631579,44 L14.6270764,35.6852027 C10.0310281,32.5933537 7,27.2926864 7,21.2727273 C7,11.7332634 14.6111593,4 24,4 C33.3888407,4 41,11.7332634 41,21.2727273 C41,27.2926864 37.9689719,32.5933537 33.3729236,35.6852027 L36.7368421,44 L11.2631579,44 Z",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("path", {
    "attrs": {
      "d": "M20,38 L20,44",
      "stroke": props.innerStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("path", {
    "attrs": {
      "d": "M28,38 L28,44",
      "stroke": props.innerStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("circle", {
    "attrs": {
      "stroke": props.innerStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.innerFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin,
      "cx": "17",
      "cy": "20",
      "r": "3"
    }
  }), h("circle", {
    "attrs": {
      "stroke": props.innerStrokeColor,
      "stroke-width": props.strokeWidth,
      "fill": props.innerFillColor,
      "fill-rule": "nonzero",
      "stroke-linejoin": props.strokeLinejoin,
      "cx": "31",
      "cy": "20",
      "r": "3"
    }
  })])])]);
});

exports.default = _default;