"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file sofa 沙发
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('sofa', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(4.000000, 8.000000)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth
    }
  }, [h("rect", {
    "attrs": {
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "x": "0",
      "y": "13",
      "width": "8",
      "height": "14"
    }
  }), h("rect", {
    "attrs": {
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "x": "32",
      "y": "13",
      "width": "8",
      "height": "14"
    }
  }), h("rect", {
    "attrs": {
      "stroke-linecap": props.strokeLinecap,
      "x": "8",
      "y": "19",
      "width": "24",
      "height": "8"
    }
  }), h("polyline", {
    "attrs": {
      "stroke-linecap": props.strokeLinecap,
      "points": "4 12 4 0 36 0 36 12"
    }
  }), h("path", {
    "attrs": {
      "d": "M4,28 L4,32",
      "stroke-linecap": props.strokeLinecap
    }
  }), h("path", {
    "attrs": {
      "d": "M36,28 L36,32",
      "stroke-linecap": props.strokeLinecap
    }
  })])])]);
});

exports.default = _default;