"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file sort-two 排序2
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('sort-two', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("g", {
    "attrs": {
      "transform": "translate(7.000000, 5.000000)",
      "stroke": props.outStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "stroke-width": props.strokeWidth
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(6.500000, 18.500000) scale(-1, -1) rotate(90.000000) translate(-6.500000, -18.500000) translate(-12.000000, 12.000000)"
    }
  }, [h("path", {
    "attrs": {
      "d": "M36,12 L0,12"
    }
  }), h("path", {
    "attrs": {
      "d": "M24.1005051,0 L36.1005051,12"
    }
  })]), h("g", {
    "attrs": {
      "transform": "translate(27.000000, 19.500000) scale(-1, 1) rotate(90.000000) translate(-27.000000, -19.500000) translate(8.500000, 12.500000)"
    }
  }, [h("path", {
    "attrs": {
      "d": "M36.1005051,2 L0.100505063,2"
    }
  }), h("path", {
    "attrs": {
      "d": "M36.1005051,2 L24.1005051,14"
    }
  })])])])])]);
});

exports.default = _default;