"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file sun-one 太阳1
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('sun-one', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("circle", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "cx": "24",
      "cy": "24",
      "r": "13"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "24",
      "cy": "3.5",
      "r": "2.5"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "38.5",
      "cy": "9.5",
      "r": "2.5"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "44.5",
      "cy": "24",
      "r": "2.5"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "38.5",
      "cy": "38.5",
      "r": "2.5"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "24",
      "cy": "44.5",
      "r": "2.5"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "9.5",
      "cy": "38.5",
      "r": "2.5"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "3.5",
      "cy": "24",
      "r": "2.5"
    }
  }), h("circle", {
    "attrs": {
      "fill": props.outStrokeColor,
      "cx": "9.5",
      "cy": "9.5",
      "r": "2.5"
    }
  })])])]);
});

exports.default = _default;