"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file surveillance-cameras-two 监控摄像头
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('surveillance-cameras-two', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("path", {
    "attrs": {
      "d": "M8.62354 9L40.4991 17.541L38.7567 20.18L34.7543 27.3898L33.0119 30.0287L19.006 26.2758L5.00007 22.523L8.62354 9Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M38.7567 20.18L42.6204 21.2153L40.5499 28.9427L34.7543 27.3898M38.7567 20.18L40.4991 17.541L8.62354 9L5.00007 22.523L19.006 26.2758M38.7567 20.18L34.7543 27.3898M34.7543 27.3898L33.0119 30.0287L19.006 26.2758M19.006 26.2758L19.006 37L5.00007 37",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;