"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file switch 切换
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('switch', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("g", {
    "attrs": {
      "transform": "translate(5.899495, 7.000000)",
      "stroke": props.outStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "stroke-width": props.strokeWidth
    }
  }, [h("g", [h("path", {
    "attrs": {
      "d": "M36.1005051,12 L0.100505063,12"
    }
  }), h("path", {
    "attrs": {
      "d": "M24.1005051,0 L36.1005051,12"
    }
  })]), h("g", {
    "attrs": {
      "transform": "translate(18.500000, 27.000000) scale(-1, 1) translate(-18.500000, -27.000000) translate(0.000000, 20.000000)"
    }
  }, [h("path", {
    "attrs": {
      "d": "M36.1005051,2 L0.100505063,2"
    }
  }), h("path", {
    "attrs": {
      "d": "M36.1005051,2 L24.1005051,14"
    }
  })])])])])]);
});

exports.default = _default;