"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file tent 帐篷
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('tent', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "fill": "none",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("path", {
    "attrs": {
      "d": "M10 12H38L39.5 18L41 24L44 36H16L13 24L11.5 18L10 12Z",
      "fill": props.outFillColor
    }
  }), h("path", {
    "attrs": {
      "d": "M10 12H38L39.5 18M10 12L4 36H16M10 12L11.5 18M16 36H44L41 24L39.5 18M16 36L13 24L11.5 18M11.5 18H39.5",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  })]);
});

exports.default = _default;