"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file text 文字
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('text', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("g", {
    "attrs": {
      "transform": "translate(6.000000, 6.000000)",
      "stroke-linejoin": props.strokeLinejoin,
      "stroke-width": props.strokeWidth
    }
  }, [h("rect", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "x": "0",
      "y": "0",
      "width": "36",
      "height": "36",
      "rx": "3"
    }
  }), h("polyline", {
    "attrs": {
      "stroke": props.innerStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "points": "10 12.9999656 10 10 26 10 26 12.9999656"
    }
  }), h("path", {
    "attrs": {
      "d": "M16,28 L20,28",
      "stroke": props.innerStrokeColor,
      "stroke-linecap": props.strokeLinecap
    }
  }), h("path", {
    "attrs": {
      "d": "M25,20 L9,20",
      "stroke": props.innerStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "transform": "translate(17.500000, 19.500000) rotate(-90.000000) translate(-17.500000, -19.500000) "
    }
  })])])])]);
});

exports.default = _default;