"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file thunderstorm 雷雨
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('thunderstorm', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("g", [h("path", {
    "attrs": {
      "d": "M9.45454545,30.9942349 C6.14241809,28.4610159 4,24.4278269 4,19.8851211 C4,12.2165805 10.105208,6 17.6363636,6 C23.9334485,6 29.2336153,10.3461769 30.8015264,16.2532944 C32.0352574,15.6159461 33.430978,15.2567474 34.9090909,15.2567474 C39.9298614,15.2567474 44,19.4011344 44,24.5134948 C44,28.3093519 41.7561905,31.571579 38.5454545,33",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }), h("path", {
    "attrs": {
      "d": "M16,22 L16,26",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "transform": "translate(16.000000, 24.000000) rotate(45.000000) translate(-16.000000, -24.000000) "
    }
  }), h("polyline", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "points": "26.999649 24 19 32.0011902 29.003972 32.0011902 21.0003052 40.0017548"
    }
  }), h("path", {
    "attrs": {
      "d": "M32,38 L32,42",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin,
      "transform": "translate(32.000000, 40.000000) rotate(45.000000) translate(-32.000000, -40.000000) "
    }
  })])])])]);
});

exports.default = _default;