"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file to-bottom 去底部
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('to-bottom', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(11.058586, 6.000000)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth
    }
  }, [h("path", {
    "attrs": {
      "d": "M26.8994949,13.9497475 L-1,13.9497475",
      "transform": "translate(12.949747, 13.949747) rotate(90.000000) translate(-12.949747, -13.949747) "
    }
  }), h("polyline", {
    "attrs": {
      "transform": "translate(12.941414, 22.000000) rotate(90.000000) translate(-12.941414, -22.000000) ",
      "points": "6.94141413 10 18.9414141 22 6.94141413 34"
    }
  }), h("path", {
    "attrs": {
      "d": "M0.941414135,36 L24.9414141,36",
      "transform": "translate(12.941414, 36.000000) rotate(180.000000) translate(-12.941414, -36.000000) "
    }
  })])])]);
});

exports.default = _default;