"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file to-top 去顶部
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('to-top', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linecap": props.strokeLinecap,
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(11.058589, 5.500000)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth
    }
  }, [h("path", {
    "attrs": {
      "d": "M26.8994949,22.5502525 L-1,22.5502525",
      "transform": "translate(12.949747, 22.550253) rotate(-90.000000) translate(-12.949747, -22.550253) "
    }
  }), h("polyline", {
    "attrs": {
      "transform": "translate(12.941411, 14.500000) rotate(-90.000000) translate(-12.941411, -14.500000) ",
      "points": "6.94141118 2.5 18.9414112 14.5 6.94141118 26.5"
    }
  }), h("path", {
    "attrs": {
      "d": "M0.941411185,0.5 L24.9414112,0.5"
    }
  })])])]);
});

exports.default = _default;