"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file umbrella 雨伞
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('umbrella', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("g", {
    "attrs": {
      "transform": "translate(4.000000, 3.000000)",
      "stroke": props.outStrokeColor,
      "stroke-linejoin": props.strokeLinejoin,
      "stroke-width": props.strokeWidth
    }
  }, [h("path", {
    "attrs": {
      "d": "M12.7272727,24 C15.1515152,21.5757576 17.5757576,20.3636364 20,20.3636364 C22.4242424,20.3636364 24.8484848,21.5757576 27.2727273,24 C30.1010101,21.5757576 32.2222222,20.3636364 33.6363636,20.3636364 C35.0505051,20.3636364 37.1717172,21.5757576 40,24 C40,12.954305 31.045695,4 20,4 C8.954305,4 0,12.954305 0,24 C2.82828283,21.5757576 4.94949495,20.3636364 6.36363636,20.3636364 C7.77777778,20.3636364 9.8989899,21.5757576 12.7272727,24 Z",
      "fill": props.outFillColor,
      "fill-rule": "nonzero"
    }
  }), h("path", {
    "attrs": {
      "d": "M20,21 L20,35.5536268 C20,38.5677816 22.4858452,41.0112369 25.5,41.0112369 C28.5141548,41.0112369 31,38.5677816 31,35.5536268",
      "stroke-linecap": props.strokeLinecap
    }
  }), h("path", {
    "attrs": {
      "d": "M20,0 L20,4",
      "stroke-linecap": props.strokeLinecap
    }
  })])])])]);
});

exports.default = _default;