"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file up-c 上-圆
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('up-c', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd"
    }
  }, [h("g", [h("circle", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth,
      "cx": "24",
      "cy": "24",
      "r": "20"
    }
  }), h("g", {
    "attrs": {
      "transform": "translate(4.000000, 4.000000)",
      "stroke-linejoin": props.strokeLinejoin,
      "stroke-width": props.strokeWidth
    }
  }, [h("circle", {
    "attrs": {
      "stroke": props.outStrokeColor,
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "cx": "20",
      "cy": "20",
      "r": "20"
    }
  }), h("polyline", {
    "attrs": {
      "stroke": props.innerStrokeColor,
      "stroke-linecap": props.strokeLinecap,
      "transform": "translate(20.000000, 18.500000) scale(1, -1) rotate(90.000000) translate(-20.000000, -18.500000) ",
      "points": "15.5 9.5 24.5 18.5 15.5 27.5"
    }
  })])])])]);
});

exports.default = _default;