"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.default = void 0;

var _runtime = require("../runtime");

/**
 * @file write 写作
 * @author Auto Generated by BD
 */

/* tslint:disable: max-line-length*/

/* eslint-disable max-len */
var _default = (0, _runtime.IconWrapper)('write', function (h, props) {
  return h("svg", {
    "attrs": {
      "width": props.size,
      "height": props.size,
      "viewBox": "0 0 48 48",
      "xmlns": "http://www.w3.org/2000/svg"
    }
  }, [h("g", {
    "attrs": {
      "stroke": "none",
      "stroke-width": props.strokeWidth,
      "fill": "none",
      "fill-rule": "evenodd",
      "stroke-linejoin": props.strokeLinejoin
    }
  }, [h("g", {
    "attrs": {
      "transform": "translate(23.701010, 23.701010) rotate(-45.000000) translate(-23.701010, -23.701010) translate(-4.798990, -4.798990)",
      "stroke": props.outStrokeColor,
      "stroke-width": props.strokeWidth
    }
  }, [h("polygon", {
    "attrs": {
      "fill": props.outFillColor,
      "fill-rule": "nonzero",
      "transform": "translate(28.798990, 28.798990) rotate(45.000000) translate(-28.798990, -28.798990) ",
      "points": "9.00025895 48.5977208 17.4852814 48.5979797 48.5979797 17.4852814 40.1126984 9 9 40.1126984"
    }
  }), h("path", {
    "attrs": {
      "d": "M38.7989899,22.7989899 L38.7989899,34.7989899",
      "stroke-linecap": props.strokeLinecap
    }
  })])])]);
});

exports.default = _default;